language: go

go:
  - 1.13.x
  - 1.x
os:
  - linux
dist: bionic

jobs:
  include:
    - stage: deploy
      if: tag IS present
      os: linux
      services:
        - docker
      script: docker run -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --privileged -v $TRAVIS_BUILD_DIR:/go/src/github.com/anishathalye/unblock -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/anishathalye/unblock mailchain/goreleaser-xcgo --rm-dist
