name: CI
on:
  push:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - ~1.11
          - ~1.12
          - ~1.13
          - ~1.14
          - ^1.15
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
